sudo: false

language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
      sudo: true
      dist: "xenial"

install:
  - travis_retry pip install tox-travis

script:
  - tox
